export const ERRORS = {
  NOT_LOGGED_IN: 'Nie jesteś zalogowany',
  NO_PERMISSIONS: 'Brak uprawnień',
  USER_CREATE_FAILED: 'Nie udało się utworzyć użytkownika',
  USER_UPDATE_FAILED: 'Nie udało się zaktualizować użytkownika',
  USER_DELETE_FAILED: 'Nie udało się usunąć użytkownika',
  PROFILE_UPDATE_FAILED: 'Nie udało się zaktualizować profilu',
  PASSWORD_CHANGE_FAILED: 'Nie udało się zmienić hasła',
  INVALID_CURRENT_PASSWORD: 'Aktualne hasło jest nieprawidłowe',
  PASSWORDS_NOT_MATCH: 'Hasła nie są identyczne',
  PASSWORD_TOO_SHORT: 'Hasło musi mieć minimum 8 znaków',
  INVALID_EMAIL: 'Nieprawidłowy format email',
  PERMISSION_GRANT_FAILED: 'Nie udało się nadać uprawnienia',
  PERMISSION_REVOKE_FAILED: 'Nie udało się usunąć uprawnienia',
  EMAIL_CHANGE_FAILED: 'Nie udało się zmienić email',
} as const

export const AVAILABLE_PERMISSIONS = [
  { key: 'konta.view', label: 'Konta - podgląd', description: 'Może widzieć listę użytkowników' },
  { key: 'konta.create', label: 'Konta - tworzenie', description: 'Może tworzyć nowych użytkowników' },
  { key: 'konta.edit', label: 'Konta - edycja', description: 'Może edytować użytkowników' },
  { key: 'konta.delete', label: 'Konta - usuwanie', description: 'Może usuwać użytkowników' },
  { key: 'konta.permissions', label: 'Konta - uprawnienia', description: 'Może zarządzać uprawnieniami' },
  { key: 'audit.view', label: 'Audit - podgląd', description: 'Może widzieć logi audytu' },
  { key: 'settings.view', label: 'Ustawienia - podgląd', description: 'Może widzieć ustawienia' },
  { key: 'settings.edit', label: 'Ustawienia - edycja', description: 'Może zmieniać ustawienia' },
  { key: 'vezvision.access', label: 'VezVision - dostęp', description: 'Może widzieć kartę/moduł VezVision' },
  { key: 'vezvision.blog.view', label: 'VezVision Blog - podgląd', description: 'Może widzieć listę i szczegóły wpisów' },
  { key: 'vezvision.blog.manage', label: 'VezVision Blog - zarządzanie', description: 'Może tworzyć, edytować i usuwać wpisy' },
  { key: 'vezvision.blog.publish', label: 'VezVision Blog - publikacja', description: 'Może publikować i wycofywać wpisy' },
  { key: 'vezvision.portfolio.view', label: 'VezVision Portfolio - podgląd', description: 'Może widzieć listę i szczegóły projektów' },
  { key: 'vezvision.portfolio.manage', label: 'VezVision Portfolio - zarządzanie', description: 'Może tworzyć, edytować i usuwać projekty' },
  { key: 'vezvision.services.view', label: 'VezVision Usługi - podgląd', description: 'Może widzieć listę i szczegóły usług' },
  { key: 'vezvision.services.manage', label: 'VezVision Usługi - zarządzanie', description: 'Może tworzyć, edytować i usuwać usługi' },
  { key: 'vezvision.faq.view', label: 'VezVision FAQ - podgląd', description: 'Może widzieć listę i szczegóły FAQ' },
  { key: 'vezvision.faq.manage', label: 'VezVision FAQ - zarządzanie', description: 'Może tworzyć, edytować i usuwać wpisy FAQ' },
  { key: 'vezvision.newsletter.view', label: 'VezVision Newsletter - podgląd', description: 'Może widzieć subskrybentów i kampanie newslettera' },
  { key: 'vezvision.newsletter.manage', label: 'VezVision Newsletter - zarządzanie', description: 'Może zarządzać subskrybentami i kampaniami newslettera' },
  { key: 'vezvision.files.view', label: 'VezVision Pliki - podgląd', description: 'Może przeglądać pliki i foldery' },
  { key: 'vezvision.files.manage', label: 'VezVision Pliki - zarządzanie', description: 'Może tworzyć foldery, uploadować, przenosić i usuwać pliki' },
  { key: 'vezvision.files.permissions.manage', label: 'VezVision Pliki - ACL folderów', description: 'Może nadawać uprawnienia per-folder (widok/upload/zarządzanie)' },
  { key: 'vezvision.settings.view', label: 'VezVision Ustawienia - podgląd', description: 'Może widzieć ustawienia VezVision' },
  { key: 'vezvision.settings.manage', label: 'VezVision Ustawienia - zarządzanie', description: 'Może edytować ustawienia VezVision' },
  { key: 'vezvision.calendar.view', label: 'VezVision Kalendarz - podgląd', description: 'Może widzieć wydarzenia w kalendarzu' },
  { key: 'vezvision.calendar.manage', label: 'VezVision Kalendarz - zarządzanie', description: 'Może tworzyć, edytować i usuwać wydarzenia' },
] as const
