export const ONE_SECOND = 1000
export const ONE_MINUTE = 60 * ONE_SECOND
export const FIVE_MINUTES = 5 * ONE_MINUTE
export const FIFTEEN_MINUTES = 15 * ONE_MINUTE
export const THIRTY_MINUTES = 30 * ONE_MINUTE
export const ONE_HOUR = 60 * ONE_MINUTE
export const ONE_DAY = 24 * ONE_HOUR
export const ONE_HOUR_SECONDS = ONE_HOUR / ONE_SECOND
export const ONE_DAY_SECONDS = ONE_DAY / ONE_SECOND
export const ONE_DAY_MS = ONE_DAY
